apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "restricted"
      enforce-version: "latest"
      audit: "restricted"
      audit-version: "latest"
      warn: "restricted"
      warn-version: "latest"
    exemptions:
      namespaces:
      - cattle-dashboards
      - cattle-epinio-system
      - cattle-fleet-system
      - cattle-gatekeeper-system
      - cattle-impersonation-system
      - cattle-logging-system
      - cattle-monitoring-system
      - cattle-neuvector-system
      - cattle-sriov-system
      - cattle-system
      - cis-operator-system
      - istio-system
      - kube-node-lease
      - kube-public
      - kube-system
      - longhorn-system